spring.application.name=api

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/somnguard}
spring.datasource.username=${POSTGRES_USER:somnguard_user}
spring.datasource.password=${POSTGRES_PASSWORD:change_me}
spring.jpa.hibernate.ddl-auto=validate
