spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    contexts: dev

logging:
  level:
    com.somnguard: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoint:
    health:
      show-details: always

app:
  jwt:
    public-key-location: classpath:keys/dev/public.pem
    private-key-location: classpath:keys/dev/private.pem